name: Build

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build docker image
      run: docker build --tag queryengine --file Dockerfile .
    - name: tag release image
      run: docker tag queryengine ${{ secrets.DOCKERHUB_USERNAME }}/dhscanner-pyswipl:x64
    - name: login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    - name: push image to Dockerhub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/dhscanner-pyswipl:x64
